server:
  port: 8081
#  port: 443
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store-password: '123456'
#    key-store: keystore.p12

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-name: oauth2-client-app
            client-id: oauth2-client-app
            client-secret: 'client secret'
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            provider: keycloak
            scope:
              - openid
              - profile
          google:
            client-id: 'client-id'
            client-secret: 'client-secret'
            scope:
              - openid
              - profile
              - email
          naver:
            client-id: 'client-id'
            client-secret: 'client-secret'
            authorization-grant-type: authorization_code
            client-name: naver-client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope:
              - profile
              - email
          kakao:
            client-id: 'client-id'
            client-secret: 'client-secret'
            authorization-grant-type: authorization_code
            client-name: client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            scope:
              - openid
              - profile_image
              - profile_nickname
              - account_email
          facebook:
            client-id: 'client-id'
            client-secret: 'client-secret'
            authorization-grant-type: authorization_code
            client-name: my-client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/facebook
            scope:
              - public_profile
              - email
#          microsoft:
#            client-id: 'client-id'
#            client-secret: 'client-secret'
#            authorization-grant-type: authorization_code
#            client-name: my-cliient-app
#            redirect-uri: http://localhost:8081/login/oauth2/code/microsoft
#            scope:
#              - user.read
        provider:
          keycloak:
            authorization-uri: http://localhost:18080/realms/master/protocol/openid-connect/auth
            token-uri: http://localhost:18080/realms/master/protocol/openid-connect/token
            issuer-uri: http://localhost:18080/realms/master
            user-info-uri: http://localhost:18080/realms/master/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:18080/realms/master/protocol/openid-connect/certs
            user-name-attribute: preferred_username
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            jwk-set-uri: https://openapi.naver.com/v1/nid/verify
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id
#            user-name-attribute: sub # OpenID Connect
#          microsoft:
#            issuer-uri: https://login.microsoftonline.com/[app-id]/v2.0
#            authorization-uri: https://login.microsoftonline.com/[app-id]/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/[app-id]/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            jwk-set-uri: https://login.microsoftonline.com/[app-id]/discovery/v2.0/keys
  mvc:
    static-path-pattern: /static/**
