server:
  port: 8081

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:18080/realms/master
          jwk-set-uri: http://localhost:18080/realms/master/protocol/openid-connect/certs
#          jws-algorithms: RS256 # RSA
#          jws-algorithms: HS256 # MAC
          jws-algorithms: RS512 # RSA 512


